Repository idno/known, pull requests merged in 2019-04, with the labels that each got.

#2370 Adding some notes about composer in upgrade docs
  README.md
  docs/install/upgrade.md
Labels: P1, Tiny thing

#2371 Fixing build status
  README.md
Labels: P3, Tiny thing

#2375 Removing h5f HTML5 shim
  README.md
  composer.json
  templates/default/shell/footerjavascript.tpl.php
  templates/default/shell/simple.tpl.php
Labels: P3, Tiny thing

#2387 Add fontawesome shim
  templates/default/shell/bootstrap.tpl.php
  templates/default/shell/simple.tpl.php
  version.known
Labels: Bug, P1, Tiny thing

#2389 Fixing a potential SSL detection bug
  Idno/Common/Page.php
Labels: Bug, P1

#2372 Move language tools into their own project
  Gruntfile.js
  composer.json
  docs/developers/languages/index.md
  languages/makepot.sh
  languages/processfile.php
Labels: P2, Tiny thing

#2377 Removing PHPCS configuration to specific dev requirements
  composer.json
  phpcs/known.xml
Labels: P3, Tiny thing

#2378 Removing SQLite3 support
  .travis.yml
  Idno/Data/Sqlite3.php
  Tests/build/config_sqlite3.ini
  warmup/schemas/sqlite3/2016102601.sql
  warmup/schemas/sqlite3/2016110301.sql
  warmup/schemas/sqlite3/2017032001.sql
  warmup/schemas/sqlite3/sqlite3.sql
Labels: P2

#2380 Removing index.html
  external/index.html
Labels: P3, Tiny thing

#2382 Ignore composer.phar
  .gitignore
Labels: P3, Tiny thing

#2384 Fontello config not used, removing
  .gitignore
Labels: P3, Tiny thing

#2383 Initial Admin/Settings skin
  Idno/Core/Account.php
  Idno/Core/Admin.php
  Idno/Core/Template.php
  css/default.css
  css/default.min.css
  js/default.min.js
  js/embeds.min.js
  js/image.min.js
  js/service-worker.min.js
  js/templates/default/shell.min.js
  templates/default/account/menu.tpl.php
  templates/default/admin/menu.tpl.php
  templates/default/forms/link.tpl.php
  templates/default/settings-shell.tpl.php
  templates/default/settings-shell/bootstrap.tpl.php
  templates/default/settings-shell/css.tpl.php
  templates/default/settings-shell/footerjavascript.tpl.php
  templates/default/settings-shell/icons.tpl.php
  templates/default/settings-shell/javascript.tpl.php
  templates/default/settings-shell/messages.tpl.php
  templates/default/settings-shell/metatags.tpl.php
  templates/default/settings-shell/nav.tpl.php
  templates/default/settings-shell/toolbar/logged-in.tpl.php
  templates/default/shell.tpl.php
  templates/default/shell/form-data.php
Labels: P1

#2386 Improved error message templates
  Idno/start.php
  statics/db.php
  statics/error-page.php
Labels: P2

#2385 Adding logged in user icon to dropdown menu
  css/default.css
  css/default.min.css
  js/default.min.js
  js/embeds.min.js
  js/image.min.js
  js/service-worker.min.js
  js/templates/default/shell.min.js
  templates/default/shell/toolbar/logged-in.tpl.php
Labels: P3, Tiny thing

#2342 Adding new MarketStreet theme
  .gitignore
  Themes/MarketStreet/.gitignore
  Themes/MarketStreet/Gruntfile.js
  Themes/MarketStreet/css/default.css
  Themes/MarketStreet/css/default.min.css
  Themes/MarketStreet/languages/marketstreet.pot
  Themes/MarketStreet/package.json
  Themes/MarketStreet/preview.png
  Themes/MarketStreet/templates/default/content/end.tpl.php
  Themes/MarketStreet/templates/default/entity/Entry.tpl.php
  Themes/MarketStreet/templates/default/entity/User.tpl.php
  Themes/MarketStreet/templates/default/entity/shell.tpl.php
  Themes/MarketStreet/templates/default/marketstreet/shell/head.tpl.php
  Themes/MarketStreet/theme.ini
  languages/source/known.pot
Labels: P3

#2395 Security: Adding some sanitisation to notifications and webmentions
  Idno/Common/Entity.php
  templates/default/content/notification/wrapper.tpl.php
  templates/default/entity/annotations/likes.tpl.php
  templates/default/entity/annotations/mentions.tpl.php
  templates/default/entity/annotations/rsvps.tpl.php
  templates/default/entity/annotations/shares.tpl.php
Labels: Bug, P1, Security
